let API_LINK;
let AUTH_API_KEY;
let CRYPTOJS_KEY;
let BCRYPT_SALT;
let SHA256_KEY;
let AWS_S3_AKEY;
let AWS_S3_SKEY;
let AWS_S3_BUCKET;
let AWS_S3_BUCKET_REGION;

if (process.env.REACT_APP_DEPLOYMENT_ENV === 'development') {
    API_LINK = process.env.REACT_APP_DEV_LINK;
    AWS_S3_AKEY = process.env.REACT_APP_DEV_AWS_AKEY;
    AWS_S3_SKEY = process.env.REACT_APP_DEV_AWS_SKEY;
    AWS_S3_BUCKET = process.env.REACT_APP_DEV_AWS_S3_BUCKET;
    AWS_S3_BUCKET_REGION = process.env.REACT_APP_DEV_AWS_S3_BUCKET_REGION;
} else if (process.env.REACT_APP_DEPLOYMENT_ENV === 'staging') {
    API_LINK = process.env.REACT_APP_TEST_LINK;
    AWS_S3_AKEY = process.env.REACT_APP_TEST_AWS_AKEY;
    AWS_S3_SKEY = process.env.REACT_APP_TEST_AWS_SKEY;
    AWS_S3_BUCKET = process.env.REACT_APP_TEST_AWS_S3_BUCKET;
    AWS_S3_BUCKET_REGION = process.env.REACT_APP_TEST_AWS_S3_BUCKET_REGION;
} else if (process.env.REACT_APP_DEPLOYMENT_ENV === 'production') {
    API_LINK = process.env.REACT_APP_PROD_LINK;
    AWS_S3_AKEY = process.env.REACT_APP_PROD_AWS_AKEY;
    AWS_S3_SKEY = process.env.REACT_APP_PROD_AWS_SKEY;
    AWS_S3_BUCKET = process.env.REACT_APP_PROD_AWS_S3_BUCKET;
    AWS_S3_BUCKET_REGION = process.env.REACT_APP_PROD_AWS_S3_BUCKET_REGION;
};

AUTH_API_KEY = process.env.REACT_APP_AUTH_API_KEY;
CRYPTOJS_KEY = process.env.REACT_APP_CRYPTOJS_KEY;
BCRYPT_SALT = process.env.REACT_APP_BCRYPT_SALT_ROUNDS;
SHA256_KEY = process.env.REACT_APP_SHA256_ROUNDS;


export { API_LINK, AUTH_API_KEY, CRYPTOJS_KEY, BCRYPT_SALT, SHA256_KEY, AWS_S3_AKEY, AWS_S3_SKEY, AWS_S3_BUCKET, AWS_S3_BUCKET_REGION };